-- DESTRUCTIVE ROLLBACK. NEVER RUN AGAINST A DATABASE CONTAINING
-- ACCEPTED SUPPORTER RECORDS WITHOUT AN APPROVED EXPORT/RESTORE PLAN.
BEGIN;
REVOKE supporter_runtime, supporter_public_reader, supporter_operator FROM CURRENT_USER;
DROP SCHEMA IF EXISTS supporter_public CASCADE;
DROP SCHEMA IF EXISTS supporter_private CASCADE;
DROP ROLE IF EXISTS supporter_runtime;
DROP ROLE IF EXISTS supporter_public_reader;
DROP ROLE IF EXISTS supporter_operator;
COMMIT;
